<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta content="IE=edge" http-equiv="X-UA-Compatible">
		<meta content="initial-scale=1.0, width=device-width" name="viewport">
		<#if (decoratedContent.subcontent?exists?has_content)>
			<#if (decoratedContent.subcontent.title?has_content)>
				<#assign pageTitle = decoratedContent.subcontent.title.render />
			</#if>
		</#if>
		<#if (pageTitle?exists?has_content)>
			<#-- set content name as page title -->
			<#assign pageTitle = decoratedContent.fields.contentName />
		</#if>
		<title>${(pageTitle)!"Help Resources and Guides"}</title>
	
		<!-- css -->
		<link href="/hc/assets/material/css/base.min.css" rel="stylesheet">
	
		<!-- css for this project -->
		<link href="/hc/assets/material/css/project.min.css" rel="stylesheet">
		<#-- material icons -->
		<link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<!-- favicon -->
		
		<!-- syntax highlighter -->
		<script type="text/javascript" src="/hc/assets/syntaxhighlighter/scripts/shCore.js"></script>
		<script type="text/javascript" src="/hc/assets/syntaxhighlighter/scripts/shBrushJScript.js"></script>
	  	<script src="/hc/assets/syntaxhighlighter/scripts/shBrushXml.js" type="text/javascript"></script>
	  	<link type="text/css" rel="stylesheet" href="/hc/assets/syntaxhighlighter/styles/shCoreDefault.css"/>
		<script type="text/javascript">SyntaxHighlighter.all();</script>
	
		<style>
			.content-heading{
				box-shadow: 0 0 4px rgba(0, 0, 0, 0.14), 0 4px 8px rgba(0, 0, 0, 0.28);
			}
			.article-content{
				margin-top:50px;
			}
			.material-icons{
				vertical-align:middle;
			}
			.author-details{
				font-style:italic;
				opacity:0.7;
			}
			.anchorific {
			    overflow-x: hidden;
			    overflow-y: auto;
			    width: 160px;
			    z-index: 10000;
			}
			.anchorific ul {
				list-style-type: none;
    			padding: 0;
    			margin-left:12px;
    			margin-top:0;
			}
			.anchorific ul li{
				line-height: 16px;
    			margin: 8px 0 0;
    			position: relative;
    		}
			.anchorific ul li a {
				-moz-user-select: none;
			    color: #212121;
			    display: block;
			    overflow: hidden;
			    text-overflow: ellipsis;
			}
			.anchorific li ul {}
			/* active class is generated by the scrollspy */
			.anchorific li.active > a {
    			color: #039be5;
				font-weight: 500;
			}
			.anchorific li.active > ul {}
			.anchor{
			}
			.document-toc{
			    border-left: 4px solid #4a148c;
    			margin-left:12px;
			}
			.document-toc > .title-content{
				font-weight:500;
    			padding-left: 12px;
			}
			.document-toc.affix{
				position:fixed;
				top:150px;
			}
			.nav-subtopics{
				margin-top:10px;
			}
			.nav-subtopics .a, .nav-subtopics a{
				padding:5px 5px 5px 10px;
			}
			hr.dashed-separator{
				border-top:1px dashed #c0c0c0;
			}
		</style>
	</head>
	<body class="avoid-fout page-purple">
		<#-- converted to html so html formatting tools can be used -->
		<#include "component://ax-XDocCenter/webapp/ax-XDocCenter/layouts/material-theme/articlePage/templateWrapper.html" parse="true"/>
	</body>
</html>